### PR TITLE
Improve the simplified chinese translation

### PR DESCRIPTION
**Pull request by huanzhang**
For easy understanding, one line of the simplified Chinese translation was improved.

### CODE REVIEW

**Comment by yumminhuang** [comment]
It looks like you missed a `(` in the link.

**Comment by huanzhang** [comment]
@yumminhuang Sorry for my carelessness. I have changed it.

**Comment by yumminhuang** [comment]
👍Looks good!

**Comment by JuanitoFatas** [comment]
Thanks @huanzhang and thank @yumminhuang for review. :+1:

**Pull request merged**
